### ISSUE TITLE
Add Dark Mode Feature to the Virtual Bubble Wrap

### ISSUE THREAD

**Issue by sirisayshello** [sirisayshello/virtual-bubble-wrap#1]
### Description:

We would like to implement a **Dark Mode** option for the Virtual Bubble Wrap website, which respects the user's system-wide dark mode setting using the `prefers-color-scheme` media query.

#### **Goals**:
- Automatically detect the user's system dark mode preference using `prefers-color-scheme`.
- Add a toggle button or switch that allows users to manually override the system preference.

#### **Suggested Steps**:
1. Use the `prefers-color-scheme` CSS media query to apply dark mode based on the user's system setting.
2. Create a toggle button or switch to allow users to manually switch between dark and light mode.

**Comment by SuvineetSingh** [comment]
Hi, @sirisayshello. I am a beginner at open-source contributions, do you mind if I go ahead and try to solve it?

**Comment by sirisayshello** [comment]
> Hi, @sirisayshello. I am a beginner at open-source contributions, do you mind if I go ahead and try to solve it?

Hi @SuvineetSingh, sure go ahead!

**Comment by SuvineetSingh** [comment]
thanks!

**Comment by SuvineetSingh** [comment]
Hi @sirisayshello , I have opened a merge request and made the necessary changes. Please have a look, and let me know if I can make any more edits according to your suggestions.
